version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./volume:/var/jenkins_home
      - ./volume/downloads:/var/jenkins_home/downloads
    environment:
      - PATH=$PATH:/var/jenkins_home/downloads/apache-maven-3.5.3/bin